services:
  api:
    build: .
    container_name: devops-api
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: mysql+pymysql://root:root@db:3306/equipment
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    container_name: devops-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: equipment
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: